In [68]:
import pandas as pd 
import numpy  as np

data = {'id'        : [1,2,3,4,5,6,7,8,9],
        'city'      : ['Asheville','Burlington','Chapel Hill','Davidson','Elizabeth City','Fargo',
                       'Grand Forks','Hettinger','Inkster'],
        'states'    : ['North Carolina','North Carolina','North Carolina','North Carolina','North Carolina',
                       'North Dakota','North Dakota','North Dakota','North Dakota'],
        'latitude'  : [35.6,36.1,35.9,35.5,36.3,46.9,47.9,46,48.2],
        'longitude' : [82.6,79.4,79.1,80.8,76.3,96.8,97,102.6,97.6]
        }

stations = pd.DataFrame(data)

In [69]:
stations

   id            city          states  latitude  longitude
0   1       Asheville  North Carolina      35.6       82.6
1   2      Burlington  North Carolina      36.1       79.4
2   3     Chapel Hill  North Carolina      35.9       79.1
3   4        Davidson  North Carolina      35.5       80.8
4   5  Elizabeth City  North Carolina      36.3       76.3
5   6           Fargo    North Dakota      46.9       96.8
6   7     Grand Forks    North Dakota      47.9       97.0
7   8       Hettinger    North Dakota      46.0      102.6
8   9         Inkster    North Dakota      48.2       97.6

In [70]:
cities1 = stations.copy()
cities1.rename(columns = {'city':'city1','latitude':'lat1','longitude':'lon1'}, inplace = True)
cities2 = stations.copy()
cities2.rename(columns = {'city':'city2','latitude':'lat2','longitude':'lon2'}, inplace = True)
df = pd.merge(cities1,cities2, on = 'states', how = 'inner')
df

,id_x,city1,states,lat1,lon1,id_y,city2,lat2,lon2
0,1,Asheville,North Carolina,35.6,82.6,1,Asheville,35.6,82.6
1,1,Asheville,North Carolina,35.6,82.6,2,Burlington,36.1,79.4
2,1,Asheville,North Carolina,35.6,82.6,3,Chapel Hill,35.9,79.1
3,1,Asheville,North Carolina,35.6,82.6,4,Davidson,35.5,80.8
4,1,Asheville,North Carolina,35.6,82.6,5,Elizabeth City,36.3,76.3
5,2,Burlington,North Carolina,36.1,79.4,1,Asheville,35.6,82.6
6,2,Burlington,North Carolina,36.1,79.4,2,Burlington,36.1,79.4
7,2,Burlington,North Carolina,36.1,79.4,3,Chapel Hill,35.9,79.1
8,2,Burlington,North Carolina,36.1,79.4,4,Davidson,35.5,80.8
9,2,Burlington,North Carolina,36.1,79.4,5,Elizabeth City,36.3,76.3
10,3,Chapel Hill,North Carolina,35.9,79.1,1,Asheville,35.6,82.6
11,3,Chapel Hill,North Carolina,35.9,79.1,2,Burlington,36.1,79.4
12,3,Chapel Hill,North Carolina,35.9,79.1,3,Chapel Hill,35.9,79.1
13,3,Chapel Hill,North Carolina,35.9,79.1,4,Davidson,35.5,80.8
14,3,Chapel Hill,North Carolina,35.9,79.1,5,Elizabeth City,36.3,76.3
15,4,Davidson,North Carolina,35.5,80.8,1,Asheville,35.6,82.6
16,4,Davidson,North Carolina,35.5,80.8,2,Burlington,36.1,79.4
17,4,Davidson,North Carolina,35.5,80.8,3,Chapel Hill,35.9,79.1
18,4,Davidson,North Carolina,35.5,80.8,4,Davidson,35.5,80.8
19,4,Davidson,North Carolina,35.5,80.8,5,Elizabeth City,36.3,76.3
20,5,Elizabeth City,North Carolina,36.3,76.3,1,Asheville,35.6,82.6
21,5,Elizabeth City,North Carolina,36.3,76.3,2,Burlington,36.1,79.4
22,5,Elizabeth City,North Carolina,36.3,76.3,3,Chapel Hill,35.9,79.1
23,5,Elizabeth City,North Carolina,36.3,76.3,4,Davidson,35.5,80.8
24,5,Elizabeth City,North Carolina,36.3,76.3,5,Elizabeth City,36.3,76.3
25,6,Fargo,North Dakota,46.9,96.8,6,Fargo,46.9,96.8
26,6,Fargo,North Dakota,46.9,96.8,7,Grand Forks,47.9,97.0
27,6,Fargo,North Dakota,46.9,96.8,8,Hettinger,46.0,102.6
28,6,Fargo,North Dakota,46.9,96.8,9,Inkster,48.2,97.6
29,7,Grand Forks,North Dakota,47.9,97.0,6,Fargo,46.9,96.8
30,7,Grand Forks,North Dakota,47.9,97.0,7,Grand Forks,47.9,97.0
31,7,Grand Forks,North Dakota,47.9,97.0,8,Hettinger,46.0,102.6
32,7,Grand Forks,North Dakota,47.9,97.0,9,Inkster,48.2,97.6
33,8,Hettinger,North Dakota,46.0,102.6,6,Fargo,46.9,96.8
34,8,Hettinger,North Dakota,46.0,102.6,7,Grand Forks,47.9,97.0
35,8,Hettinger,North Dakota,46.0,102.6,8,Hettinger,46.0,102.6
36,8,Hettinger,North Dakota,46.0,102.6,9,Inkster,48.2,97.6
37,9,Inkster,North Dakota,48.2,97.6,6,Fargo,46.9,96.8
38,9,Inkster,North Dakota,48.2,97.6,7,Grand Forks,47.9,97.0
39,9,Inkster,North Dakota,48.2,97.6,8,Hettinger,46.0,102.6
40,9,Inkster,North Dakota,48.2,97.6,9,Inkster,48.2,97.6

In [71]:
df = df[df.id_x < df.id_y][['states','city1','lat1','lon1','city2','lat2','lon2']]

In [72]:
df

            states        city1  lat1   lon1           city2  lat2   lon2
1   North Carolina    Asheville  35.6   82.6      Burlington  36.1   79.4
2   North Carolina    Asheville  35.6   82.6     Chapel Hill  35.9   79.1
3   North Carolina    Asheville  35.6   82.6        Davidson  35.5   80.8
4   North Carolina    Asheville  35.6   82.6  Elizabeth City  36.3   76.3
7   North Carolina   Burlington  36.1   79.4     Chapel Hill  35.9   79.1
8   North Carolina   Burlington  36.1   79.4        Davidson  35.5   80.8
9   North Carolina   Burlington  36.1   79.4  Elizabeth City  36.3   76.3
13  North Carolina  Chapel Hill  35.9   79.1        Davidson  35.5   80.8
14  North Carolina  Chapel Hill  35.9   79.1  Elizabeth City  36.3   76.3
19  North Carolina     Davidson  35.5   80.8  Elizabeth City  36.3   76.3
26    North Dakota        Fargo  46.9   96.8     Grand Forks  47.9   97.0
27    North Dakota        Fargo  46.9   96.8       Hettinger  46.0  102.6
28    North Dakota        Fargo  46.9   96.8         Inkster  48.2   97.6
31    North Dakota  Grand Forks  47.9   97.0       Hettinger  46.0  102.6
32    North Dakota  Grand Forks  47.9   97.0         Inkster  48.2   97.6
36    North Dakota    Hettinger  46.0  102.6         Inkster  48.2   97.6

In [73]:
df['distance'] = np.sqrt(((df['lat2']-df['lat1'])*(df['lat2']-df['lat1']) + (df['lon2']-df['lon1'])*(df['lon2']-df['lon1'])))
df['distance'] = df['distance'].round(2)

In [74]:
df

,states,city1,lat1,lon1,city2,lat2,lon2,distance
1,North Carolina,Asheville,35.6,82.6,Burlington,36.1,79.4,3.24
2,North Carolina,Asheville,35.6,82.6,Chapel Hill,35.9,79.1,3.51
3,North Carolina,Asheville,35.6,82.6,Davidson,35.5,80.8,1.80
4,North Carolina,Asheville,35.6,82.6,Elizabeth City,36.3,76.3,6.34
7,North Carolina,Burlington,36.1,79.4,Chapel Hill,35.9,79.1,0.36
8,North Carolina,Burlington,36.1,79.4,Davidson,35.5,80.8,1.52
9,North Carolina,Burlington,36.1,79.4,Elizabeth City,36.3,76.3,3.11
13,North Carolina,Chapel Hill,35.9,79.1,Davidson,35.5,80.8,1.75
14,North Carolina,Chapel Hill,35.9,79.1,Elizabeth City,36.3,76.3,2.83
19,North Carolina,Davidson,35.5,80.8,Elizabeth City,36.3,76.3,4.57
26,North Dakota,Fargo,46.9,96.8,Grand Forks,47.9,97.0,1.02
27,North Dakota,Fargo,46.9,96.8,Hettinger,46.0,102.6,5.87
28,North Dakota,Fargo,46.9,96.8,Inkster,48.2,97.6,1.53
31,North Dakota,Grand Forks,47.9,97.0,Hettinger,46.0,102.6,5.91
32,North Dakota,Grand Forks,47.9,97.0,Inkster,48.2,97.6,0.67
36,North Dakota,Hettinger,46.0,102.6,Inkster,48.2,97.6,5.46

In [75]:
df['ranks'] = df.groupby('states')['distance'].rank(method = 'first',ascending = False)
df[df.ranks == 1][['states','city1','city2','distance']]

            states        city1           city2  distance
4   North Carolina    Asheville  Elizabeth City      6.34
31    North Dakota  Grand Forks       Hettinger      5.91